-- Supabase catalog schema + RLS
-- Run this in Supabase SQL editor before importing catalog data.

begin;

create extension if not exists pgcrypto;

create table if not exists public.categories (
    id bigint generated by default as identity primary key,
    name text not null,
    slug text not null unique,
    description text,
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.products (
    id bigint generated by default as identity primary key,
    category_id bigint references public.categories(id) on delete set null,
    name text not null,
    slug text not null unique,
    description text,
    price numeric(10, 2) not null check (price >= 0),
    stock integer not null default 0 check (stock >= 0),
    flavor text,
    color text,
    scent text,
    size text,
    is_featured boolean not null default false,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.product_images (
    id bigint generated by default as identity primary key,
    product_id bigint not null references public.products(id) on delete cascade,
    original_image text,
    processed_image text,
    alt_text text,
    is_primary boolean not null default false,
    created_at timestamptz not null default now()
);

create index if not exists idx_categories_is_active on public.categories(is_active);
create index if not exists idx_products_category on public.products(category_id);
create index if not exists idx_products_is_active on public.products(is_active);
create index if not exists idx_products_is_featured on public.products(is_featured);
create index if not exists idx_product_images_product on public.product_images(product_id);
create unique index if not exists uq_product_images_primary_per_product
    on public.product_images(product_id)
    where is_primary = true;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_products_set_updated_at on public.products;
create trigger trg_products_set_updated_at
before update on public.products
for each row
execute function public.set_updated_at();

alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;

-- Public read access for storefront users.
drop policy if exists categories_public_read_active on public.categories;
create policy categories_public_read_active
on public.categories
for select
to anon, authenticated
using (is_active = true);

drop policy if exists products_public_read_active on public.products;
create policy products_public_read_active
on public.products
for select
to anon, authenticated
using (is_active = true);

drop policy if exists product_images_public_read_active_products on public.product_images;
create policy product_images_public_read_active_products
on public.product_images
for select
to anon, authenticated
using (
    exists (
        select 1
        from public.products p
        where p.id = product_images.product_id
          and p.is_active = true
    )
);

-- Optional admin/editor policies for signed-in users.
-- Keep these disabled unless you need direct browser writes.
create policy categories_authenticated_write on public.categories
for all to authenticated
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');
--
create policy products_authenticated_write on public.products
for all to authenticated
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');
--
create policy product_images_authenticated_write on public.product_images
for all to authenticated
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

commit;
